x-app-env: &app-env
  ENVIRONMENT: ${ENVIRONMENT:-local}
  POSTGRES_USER: ${POSTGRES_USER:-admin}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?err}
  POSTGRES_DB: ${POSTGRES_DB:-starrag}
  POSTGRES_HOST: postgres
  POSTGRES_PORT: 5432
  REDIS_URL: redis://redis:6379/0
  MINIO_ENDPOINT: minio:9000
  MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
  MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:?err}
  GEMINI_API_KEY: ${GEMINI_API_KEY:?err}

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: starrag-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?err}
      POSTGRES_DB: ${POSTGRES_DB:-starrag}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d starrag" ]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio
    container_name: starrag-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:?err}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - miniodata:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: starrag-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  api:
    build: .
    container_name: starrag-api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      <<: *app-env
    volumes:
      - .:/app
      - /app/.venv
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy

  celery-ingestion:
    build: .
    container_name: starrag-ingestion
    command: celery -A app.workers.celery_app worker --loglevel=info --pool=threads --concurrency=10
    ports:
      - "8001:8001"
    environment:
      <<: *app-env
    volumes:
      - .:/app
      - /app/.venv
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy

  celery-beat:
    build: .
    container_name: starrag-beat
    command: celery -A app.workers.celery_app beat --loglevel=info
    environment:
      <<: *app-env
    volumes:
      - .:/app
      - /app/.venv
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy

  prometheus:
    image: prom/prometheus:latest
    container_name: starrag-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - promdata:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    depends_on:
      - api

volumes:
  pgdata:
  miniodata:
  promdata:
